import type { BlogFaq, BlogSection, BlogSource } from "@/lib/blog-types";

export type BlogPost = {
  slug: string;
  cluster: string;
  title: string;
  description: string;
  published: string;
  modified: string;
  readTime: string;
  lead: string;
  sections: BlogSection[];
  conclusion: string;
  faqs: BlogFaq[];
  sources: BlogSource[];
  serviceHref: string;
  primaryKeyword?: string;
  secondaryKeywords?: string[];
  searchIntent?: string;
  checklist?: string[];
};

const googleHelpful = "https://developers.google.com/search/docs/fundamentals/creating-helpful-content";
const googleStructured = "https://developers.google.com/search/docs/appearance/structured-data/intro-structured-data";
const googleArticle = "https://developers.google.com/search/docs/appearance/structured-data/article";
const webVitals = "https://web.dev/articles/vitals";
const webCls = "https://web.dev/articles/optimize-cls";

const common = {
  geo: [{ label: "Google: helpful, reliable, people-first content", href: googleHelpful }, { label: "Google: structured data", href: googleStructured }, { label: "Google: Article structured data", href: googleArticle }],
  vitals: [{ label: "web.dev: Web Vitals", href: webVitals }, { label: "web.dev: avoiding layout shifts", href: webCls }],
  security: [{ label: "NIST: Secure Software Development Framework", href: "https://csrc.nist.gov/Projects/ssdf" }, { label: "OWASP Top 10", href: "https://owasp.org/www-project-top-ten/" }],
  ai: [{ label: "NIST AI Risk Management Framework", href: "https://www.nist.gov/itl/ai-risk-management-framework" }, { label: "OWASP risks for LLM applications", href: "https://owasp.org/www-project-top-10-for-large-language-model-applications/" }],
} satisfies Record<string, BlogSource[]>;

const faq = (question: string, answer: string): BlogFaq => ({ question, answer });
const section = (heading: string, ...paragraphs: string[]): BlogSection => ({ heading, paragraphs });

const brief = (primaryKeyword: string, secondaryKeywords: string[], searchIntent: string, checklist: string[]) => ({
  primaryKeyword,
  secondaryKeywords,
  searchIntent,
  checklist,
});

const briefs: Record<string, ReturnType<typeof brief>> = {
  "optimise-uk-website-google-ai-overviews": brief("optimise website for Google AI Overviews", ["Google AI Overview SEO", "GEO for UK businesses", "how to appear in AI Overviews"], "Informational guide for a UK business owner or technical marketer", ["Check the page is crawlable and indexable", "Answer one customer question near the top", "Add visible authorship and source links", "Measure qualified traffic and prompt visibility separately"]),
  "technical-foundations-for-geo": brief("technical SEO for GEO", ["GEO technical SEO", "AI search crawlability", "schema markup for AI search"], "Technical how-to guide for a search professional", ["Test status, robots, canonical, and sitemap", "Use schema that matches visible content", "Link entities and supporting pages clearly", "Inspect the deployed HTML"]),
  "technical-seo-ai-search-audit": brief("technical SEO audit", ["AI search audit", "technical SEO checklist", "SEO audit process"], "Commercial investigation and practical how-to guide", ["Start with commercially important URLs", "Check access before content", "Separate lab and field performance data", "Assign an owner and validation test"]),
  "programmatic-seo-without-thin-content": brief("programmatic SEO", ["programmatic SEO strategy", "avoid thin content", "SEO pages at scale"], "Informational guide for a team considering scaled publishing", ["Define a distinct page job", "Record data sources and freshness", "Block incomplete records from publishing", "Review indexation and duplication"]),
  "secure-accessible-website-build-checklist": brief("website development checklist", ["accessible website checklist", "secure website development", "website Core Web Vitals"], "Checklist intent for a business owner planning a build", ["Test keyboard and screen reader flows", "Reserve space for media", "Keep secrets server-side", "Run link, security, and performance checks"]),
  "when-to-build-custom-software": brief("when to build custom software", ["custom software vs off the shelf", "build or buy software", "custom application benefits"], "Decision guide for a business evaluating an internal build", ["Map the current workflow", "Compare configuration, integration, and custom build", "Model ownership and failure cost", "Launch one complete vertical slice"]),
  "connect-crm-erp-systems-safely": brief("CRM ERP integration", ["how to integrate CRM and ERP", "safe systems integration", "CRM data synchronisation"], "Technical how-to guide for an operations or engineering buyer", ["Define field ownership", "Use stable IDs and idempotency", "Separate retryable and permanent failures", "Reconcile records and totals"]),
  "ai-agent-or-fixed-automation": brief("AI agent vs automation", ["AI agent or workflow automation", "when to use an AI agent", "AI automation decision framework"], "Comparison guide for a business deciding on an AI workflow", ["Classify the workflow", "Estimate failure impact", "Constrain tools and side effects", "Evaluate real anonymised cases"]),
  "introduce-ai-automation-with-control": brief("how to implement AI automation", ["safe AI automation", "AI automation governance", "human in the loop AI"], "Practical implementation guide for an operations leader", ["Choose a reversible task", "Keep permissions outside the model", "Run shadow mode", "Define a pause and fallback process"]),
  "production-ready-ai-agent-architecture": brief("production-ready AI agent", ["AI agent architecture", "AI agent evaluation", "RAG production checklist"], "Technical architecture guide for an engineering buyer", ["Give tools typed contracts", "Test retrieval and prompt injection", "Log traces and costs", "Maintain an evaluation set"]),
  "measure-ai-automation-performance": brief("measure AI automation", ["AI automation metrics", "AI ROI measurement", "AI workflow KPIs"], "Measurement guide for a business owner or product team", ["Capture a baseline", "Track quality and review effort", "Connect metrics to business outcomes", "Set rollback thresholds"]),
  "choose-technical-seo-development-partner": brief("choose a technical SEO agency", ["technical SEO agency checklist", "SEO partner questions", "how to choose a web development partner"], "Commercial investigation guide for a buyer", ["Ask to see the delivery mechanism", "Check account ownership", "Require a measurement plan", "Reject ranking and citation guarantees"]),
  "seo-writing-guide": brief("SEO writing", ["how to write for SEO", "SEO content writing", "SEO writing tips", "content optimisation"], "Informational how-to guide for a marketer or subject expert", ["Choose one primary query", "Map related questions to sections", "Match the result format", "Add evidence and descriptive links", "Review title, metadata, and readability", "Measure outcomes after publication"]),
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "optimise-uk-website-google-ai-overviews", cluster: "Search and GEO", title: "How to optimise a UK website for Google AI Overviews",
    description: "A practical UK guide to useful content, crawlable pages, clear entities, and evidence that can support visibility in Google AI Overviews.", published: "2026-08-25", modified: "2026-08-25", readTime: "8 min read",
    lead: "Google AI Overviews do not create a separate shortcut around search fundamentals. A UK business still needs a fast, crawlable site, a page that answers a real question, and evidence that makes the answer trustworthy. The opportunity is to make the best answer easy to retrieve and easy to verify.",
    sections: [section("Start with the answer a customer needs", "Choose one clear question for each page. Put the direct answer near the top, then explain the conditions, examples, exceptions, and next action. This creates a useful page for a person and a well-defined source for an answer system.", "Avoid writing a page for a vague list of related phrases. A focused page can cover natural variations, but it should have one job and one accountable owner in the site architecture."), section("Make expertise visible", "Name the author, link to a useful author profile, show the date reviewed, and explain where claims come from. For regulated or financial topics, add appropriate review and qualification information rather than implying expertise through tone.", "Use first-hand evidence where it exists: a delivery method, an anonymised process, a measured result, or a limitation discovered in real work. Do not copy summaries from other ranking pages and call that original research."), section("Build the retrieval layer", "Give important pages stable URLs, descriptive titles, logical headings, internal links, and valid structured data that matches visible content. Check robots rules, canonicals, status codes, rendering, and XML sitemap coverage in Search Console.", "There is no ethical way to promise a citation in an AI answer. The durable target is a source that is clear, useful, technically available, and supported by relevant authority across the web.")],
    conclusion: "The strongest AI Overview strategy is still good publishing with better source clarity. Answer one useful question, prove what you know, connect the page to the rest of the site, and measure qualified visits rather than chasing a single screenshot.",
    faqs: [faq("Can a UK business guarantee a Google AI Overview citation?", "No. AI Overviews vary by query, location, device, language, and system changes. A business can improve the quality and discoverability of its sources, but cannot guarantee a particular citation."), faq("Does FAQ schema make a page appear in AI Overviews?", "No. Structured data helps systems understand a page when it accurately describes visible content, but Google does not guarantee a rich result or AI Overview appearance."), faq("How often should an AI search page be updated?", "Review it when the underlying guidance, service, evidence, or customer question changes. Do not change a date without making a meaningful content improvement.")], sources: common.geo, serviceHref: "/grow/geo",
  },
  {
    slug: "technical-foundations-for-geo", cluster: "Search and GEO", title: "Technical foundations for GEO: crawlability, schema, and AI access",
    description: "The technical SEO foundations that help conventional search and generative systems discover, interpret, and connect your content.", published: "2026-08-25", modified: "2026-08-25", readTime: "7 min read",
    lead: "Generative Engine Optimisation starts with access. If a crawler cannot fetch a page, understand its primary subject, or connect it to the rest of your site, better copy cannot rescue the source.",
    sections: [section("Audit access before markup", "Check that important URLs return a successful status, are not blocked by robots.txt or a noindex directive, and are present in the canonical and sitemap strategy. Test the rendered HTML, not only the source your framework generates during development.", "A clean information architecture is an AI access feature. Keep service pages, evidence, author pages, and supporting articles connected with descriptive links so their relationships are explicit."), section("Use structured data as a label", "JSON-LD can clarify whether a page is an Article, Service, Organisation, or BreadcrumbList. It cannot turn an empty page into a useful source. Every marked property should describe information visible to the visitor.", "Validate markup with Google's Rich Results Test, then inspect the deployed URL. A valid schema object is not a ranking guarantee and should never be used to hide claims from readers."), section("Design for extraction and verification", "Use one descriptive H1, short answer-first sections, named authors, dates, and links to primary sources. State definitions and limitations plainly. This helps readers scan and gives retrieval systems less ambiguity.", "Measure crawling and search performance in Search Console, then test representative prompts as a separate observation. Prompt visibility is directional evidence, not a replacement for analytics or rankings.")],
    conclusion: "GEO is an information architecture and evidence discipline. Improve access first, make entities and relationships explicit, and publish answers that stand up when someone follows the source link.",
    faqs: [faq("Is GEO a replacement for technical SEO?", "No. GEO and technical SEO share crawlability, page quality, entities, internal links, and authority. GEO adds attention to retrieval, answer clarity, and how systems represent sources."), faq("Which schema types should a blog use?", "Use BlogPosting or Article for the article, BreadcrumbList for navigation context, and FAQPage only when the questions and answers are visible on the page and genuinely useful."), faq("Does JavaScript prevent AI systems from reading content?", "Not always, but server-rendered HTML gives crawlers and browsers earlier access to the main content. Keep critical copy, links, and headings available in the initial response where practical.")], sources: common.geo, serviceHref: "/grow/technical-seo",
  },
  {
    slug: "technical-seo-ai-search-audit", cluster: "Search and GEO", title: "How to run a technical SEO and AI search audit",
    description: "A practical audit framework covering crawlability, indexation, rendering, entities, source quality, and Core Web Vitals.", published: "2026-08-25", modified: "2026-08-25", readTime: "9 min read",
    lead: "An audit should end with decisions, not a spreadsheet of warnings. Start with the pages that matter commercially, find the constraint that prevents them working, and attach every recommendation to a measurable outcome.",
    sections: [section("Map the pages that earn attention", "List the pages that receive organic impressions, qualified visits, enquiries, or assisted conversions. Compare that list with the pages the business needs to be found for. The gaps are often more valuable than a generic site-wide score.", "Group URLs by intent and template. A problem affecting one page type can be fixed once at the owning component or route rather than repeated page by page."), section("Trace access to understanding", "Check status codes, redirects, canonicals, robots rules, XML sitemaps, internal links, duplicate templates, and rendered content. Then inspect whether title, H1, copy, schema, and links agree about the page's subject.", "For AI search, record whether the organisation, services, authors, evidence, and locations are described consistently. Ambiguous entities create weak retrieval even when individual pages look polished."), section("Prioritise by impact and effort", "Fix broken access and indexation before rewriting paragraphs. Address slow server responses, oversized critical assets, unexpected layout shifts, and client-side rendering that delays the main answer. Use field data when available and lab data for controlled diagnosis.", "Finish with an owner, expected outcome, implementation order, and validation check. Re-crawl after deployment and compare Search Console and analytics data over a sensible period.")],
    conclusion: "A good audit is a route from evidence to action. It makes the important pages accessible, understandable, quick to use, and easier to trust across search journeys.",
    faqs: [faq("How often should a technical SEO audit run?", "Run a focused audit after major releases, migrations, or template changes, and schedule a broader review often enough to catch drift. The right frequency depends on release volume and site complexity."), faq("Should Core Web Vitals be the first audit priority?", "Only when performance is the controlling problem. Broken canonicals, blocked pages, or unclear intent can be more damaging. Prioritise the issue that prevents important pages from being discovered, understood, or used."), faq("What makes an AI search audit different?", "It adds entity clarity, source quality, authorship, citation context, answer structure, and representative prompt observation to the normal crawl and page experience checks.")], sources: [...common.geo, { label: "PageSpeed Insights", href: "https://pagespeed.web.dev/" }], serviceHref: "/grow/technical-seo",
  },
  {
    slug: "programmatic-seo-without-thin-content", cluster: "Search and GEO", title: "Programmatic SEO that does not create thin content",
    description: "How to scale useful landing pages with unique data, editorial rules, internal links, and publishing controls.", published: "2026-08-25", modified: "2026-08-25", readTime: "8 min read",
    lead: "Programmatic SEO is not a licence to multiply near-identical pages. It is a publishing system for topics where structured data can answer distinct needs better than one generic page.",
    sections: [section("Begin with a real page job", "A location, product, comparison, or dataset page should exist because people need that specific answer. Define the audience, query intent, source data, and decision the page helps someone make before writing the template.", "If the only difference between pages is a place name, delete the set. A page needs unique evidence, useful interpretation, or a genuinely distinct task."), section("Put data quality ahead of volume", "Record the source, refresh date, coverage, and missing values for every field. Expose useful facts in the page, explain the method, and do not fill gaps with invented prose.", "Use noindex or a publishing gate for records that fail minimum completeness. A smaller set of strong pages is easier to maintain, link, and earn authority for."), section("Create a network, not an island", "Connect generated pages to a hub, relevant service page, nearby alternatives, and the source or methodology page. Make the links useful to a person comparing options, not only to a crawler.", "Monitor indexation, impressions, engagement, conversions, and duplication. Stop expanding when the data or editorial review cannot keep pace.")],
    conclusion: "Scaled SEO works when scale describes the data and workflow, not a shortcut around editorial judgement. Publish fewer pages with stronger evidence and a clear reason to exist.",
    faqs: [faq("What is thin content in programmatic SEO?", "It is content that offers little original value, evidence, or useful distinction beyond another page, even when the URL and keyword have changed."), faq("How many programmatic pages should launch first?", "Launch the smallest representative set that lets you validate data quality, intent, templates, internal links, and conversion behaviour. Expand only after those checks pass."), faq("Can AI write programmatic SEO pages?", "Automation can assist with formatting or drafts, but it should not manufacture facts or replace subject review. Google recommends people-first content with original value and clear accountability.")], sources: [{ label: "Google: people-first content", href: googleHelpful }, { label: "Google: scaled content abuse policy", href: "https://developers.google.com/search/docs/essentials/spam-policies#scaled-content-abuse" }], serviceHref: "/grow/programmatic-seo",
  },
  {
    slug: "secure-accessible-website-build-checklist", cluster: "Web and software", title: "What a secure, accessible website build should include",
    description: "A practical website development checklist for accessibility, security, content structure, maintainability, and performance.", published: "2026-08-25", modified: "2026-08-25", readTime: "7 min read",
    lead: "A quality website is more than a visual layer. It should communicate its purpose to assistive technology, protect user data, render quickly, and remain understandable to the next person who has to change it.",
    sections: [section("Make the interface operable", "Use semantic headings, landmarks, labels, keyboard access, visible focus, sufficient contrast, and meaningful link text. Test the actual flows with a keyboard and a screen reader, not only an automated scan.", "Reserve space for images and embeds, avoid unexpected movement, and keep tap targets comfortable on small screens. Accessibility and Core Web Vitals often improve together when the markup is deliberate."), section("Reduce the attack surface", "Collect only the data the journey needs, validate it on the server, keep secrets out of the client, and restrict third-party scripts. Keep dependencies current and define who receives security alerts.", "Use secure headers, least-privilege credentials, rate limits where forms or APIs need them, and clear error handling that does not disclose internal details."), section("Ship a maintainable system", "Give content a clear ownership model, keep routes predictable, use reusable components, and document the decisions that affect deployment or integrations. Add automated checks for links, types, lint, and build output.", "Measure real-user performance after launch. A passing lab score is useful for regression testing, but field data shows what visitors actually experience across devices and networks.")],
    conclusion: "The best build makes the right behaviour the easy behaviour. Semantic HTML, restrained dependencies, explicit content ownership, and field measurement create a site that stays fast and dependable after launch.",
    faqs: [faq("What should be tested before a website launch?", "Test keyboard and screen reader flows, mobile layouts, forms, broken links, metadata, structured data, redirects, security headers, analytics, sitemap output, and Core Web Vitals in both lab and field tools where data exists."), faq("Does accessibility improve SEO?", "Accessible markup can improve how users and systems understand and navigate a page, but accessibility is its own user need and should not be treated only as an SEO tactic."), faq("What is the most common source of layout shift?", "Images, embeds, injected content, and fonts without reserved dimensions or predictable space are common causes. Explicit dimensions and reserved containers reduce avoidable shifts.")], sources: [...common.vitals, ...common.security], serviceHref: "/build/website-development",
  },
  {
    slug: "when-to-build-custom-software", cluster: "Web and software", title: "When should a business build custom software?",
    description: "A decision framework for choosing configuration, integration, or a focused custom application when existing tools create repeated work.", published: "2026-08-25", modified: "2026-08-25", readTime: "7 min read",
    lead: "Custom software makes sense when a repeated business process is valuable enough to own and specific enough that configuration cannot remove the friction. The decision should start with the workflow, not the technology.",
    sections: [section("Measure the repeated cost", "Document the steps, handoffs, errors, waiting time, duplicate entry, exceptions, training cost, and the opportunity cost of slow decisions.", "If the pain is caused by disconnected systems, an integration may be enough. If the process itself is unclear, software will preserve the confusion at a higher speed."), section("Compare the three paths", "Configuration is usually the lowest-risk path when the process is common and the product fits. Integration is useful when the systems are right but the handoff is missing. Custom software earns its place when the workflow, data model, or user experience is genuinely differentiating.", "Model implementation cost, ongoing ownership, security, data migration, failure recovery, and exit options. A small focused application is often easier to govern than a large platform ambition."), section("Start with a thin vertical slice", "Choose one complete workflow and make it usable from input to outcome. Establish permissions, audit events, validation, backups, and operational ownership before expanding the feature list.", "Instrument the result: completion time, error rate, manual touches, adoption, and business outcome. This turns a build into an accountable operating improvement.")],
    conclusion: "Build custom software when ownership creates a measurable advantage and the organisation is ready to operate it. Start narrow, secure the core workflow, and let evidence earn the next release.",
    faqs: [faq("How do I know whether I need custom software or an integration?", "Map the workflow. If existing tools meet the need but data or actions do not move between them, integration is likely the better first step. Custom software is more appropriate when the workflow or data model is unique."), faq("How long should a first custom software release take?", "It depends on risk, integrations, and scope. A useful first release should cover one complete workflow with security and operational basics rather than attempting the whole roadmap."), faq("Who owns custom software after launch?", "The business should own the outcome, access decisions, data governance, and prioritisation. A technical partner can maintain the system, but ownership cannot be outsourced completely.")], sources: common.security, serviceHref: "/build/custom-software",
  },
  {
    slug: "connect-crm-erp-systems-safely", cluster: "Web and software", title: "How to connect CRM, ERP, and internal systems safely",
    description: "The identifiers, permissions, validation, retries, and reconciliation a production CRM and ERP integration needs.", published: "2026-08-25", modified: "2026-08-25", readTime: "8 min read",
    lead: "A production integration is a data contract with failure handling. The happy path is the easy part. Reliability comes from deciding what a record means, who can change it, and how the system recovers when a request is late or duplicated.",
    sections: [section("Define ownership and identity", "For each field, name the source of truth, permitted direction, format, and owner. Use stable external IDs and an explicit mapping table instead of matching records by a mutable name or email alone.", "Write down what happens when two systems disagree. Silent overwrites are not reconciliation; they are delayed incidents."), section("Make every request safe to repeat", "Use idempotency keys, bounded retries with backoff, timeouts, dead-letter handling, and structured logs. Separate transient transport failures from validation or permission failures so the response is actionable.", "Validate at the boundary and protect credentials with least privilege. Do not pass more personal or commercial data between systems than the workflow needs."), section("Reconcile, monitor, and rehearse", "Run scheduled comparisons for records and totals that should agree. Alert on age, volume, failure rate, and unusual drift rather than waiting for a person to notice a missing customer.", "Test duplicate events, partial outages, expired tokens, schema changes, and replay. An integration is operational software and needs a runbook, owner, and recovery path.")],
    conclusion: "Safe integrations are designed around ownership, repeatability, and recovery. When the contract is explicit, the systems can move data quickly without turning every exception into a manual investigation.",
    faqs: [faq("What is the most important part of a CRM and ERP integration?", "A clear data contract. Define identifiers, field ownership, allowed states, validation, error behaviour, and reconciliation before choosing the transport or middleware."), faq("Should an integration retry every failed request?", "No. Retry transient failures with limits and backoff. Validation, authentication, permission, and conflict failures usually need correction or review rather than repetition."), faq("How do you test an integration?", "Test normal events, duplicates, out-of-order events, timeouts, rate limits, expired credentials, malformed data, partial outages, replay, and reconciliation against known fixtures.")], sources: [{ label: "OWASP API Security Top 10", href: "https://owasp.org/API-Security/editions/2023/en/0x11-t10/" }, ...common.security], serviceHref: "/build/systems-integrations",
  },
  {
    slug: "ai-agent-or-fixed-automation", cluster: "AI and automation", title: "Should your business use an AI agent or a fixed automation?",
    description: "A decision framework for choosing the simplest reliable pattern for a real operational workflow.", published: "2026-08-25", modified: "2026-08-25", readTime: "7 min read",
    lead: "Use a fixed automation when the steps and rules are known. Consider an AI agent when the input is variable, the task requires bounded judgement, and the outcome can be checked before it changes anything important.",
    sections: [section("Classify the workflow first", "Write the trigger, inputs, decisions, tools, output, and failure cost. If a decision table covers the process cleanly, deterministic code is usually more predictable, cheaper, and easier to test.", "An agent is a fit for controlled ambiguity, such as classifying an enquiry or finding information across approved sources. It is a poor fit for an unbounded instruction with irreversible side effects."), section("Put boundaries around judgement", "Give the model only the tools and data it needs, validate structured outputs, constrain allowed actions, and require approval for high-impact changes. Treat retrieved text as data, not as trusted instructions.", "Log the prompt context, tool calls, result, reviewer action, latency, and cost. Without that trail, a successful demo cannot become a dependable process."), section("Evaluate the outcome", "Create a test set from real anonymised cases, including difficult and adversarial examples. Measure accuracy, refusal quality, escalation rate, review time, cost, and downstream business effect.", "Release gradually with a fallback path. The system should fail visibly and recoverably, not quietly invent confidence.")],
    conclusion: "An agent is not an upgrade from an automation. It is a different reliability tradeoff. Choose it only where flexible interpretation creates enough value to justify evaluation, controls, and review.",
    faqs: [faq("What is the difference between an AI agent and an automation?", "A fixed automation follows defined rules and steps. An AI agent can interpret variable inputs and choose among bounded tools or actions, which adds flexibility and uncertainty."), faq("Should an AI agent be allowed to send messages automatically?", "Only after the risk, permissions, validation, and review threshold are clear. External or irreversible actions should usually have approval or a narrow allow-list."), faq("How do you measure an AI agent in production?", "Track task success, factual or policy errors, escalation, reviewer effort, latency, cost, tool failures, and the business result. Model quality alone is not enough.")], sources: common.ai, serviceHref: "/scale/ai-agents",
  },
  {
    slug: "introduce-ai-automation-with-control", cluster: "AI and automation", title: "How to introduce AI automation without losing control",
    description: "A controlled rollout plan for AI automation with permissions, validation, human review, evaluation, monitoring, and escalation.", published: "2026-08-25", modified: "2026-08-25", readTime: "8 min read",
    lead: "Control is not a brake on AI automation. It is the operating design that makes a useful system safe to trust. Start with a narrow workflow where the result can be reviewed and the fallback is clear.",
    sections: [section("Choose a reversible first task", "Good first candidates are summarisation, classification, routing, drafting, and retrieval with a human decision. Avoid beginning with payments, account changes, legal commitments, or anything that cannot be undone.", "Set an explicit success threshold and decide what happens below it. A workflow without a stop condition is not ready for automation."), section("Separate access from intelligence", "Keep identity, permissions, validation, and side effects in application code. The model may propose an action, but a controlled layer should decide whether that action is allowed and well-formed.", "Mask sensitive information where possible, log access, and define retention. Security decisions should not depend on the model following an instruction perfectly."), section("Roll out with evidence", "Run in shadow mode, compare outputs with the existing process, then introduce a small percentage of live work. Review errors by category and update prompts, tools, rules, or training material based on evidence.", "Monitor drift in inputs, output quality, cost, and human override. Assign an owner who can pause the workflow quickly.")],
    conclusion: "A controlled rollout turns AI from a novelty into an accountable process. Limit the blast radius, keep permissions outside the model, and let measured performance decide whether the system expands.",
    faqs: [faq("What should an AI automation never control by itself?", "There is no universal list, but irreversible, high-impact, regulated, financial, security, and personal-data actions need explicit risk review, narrow permissions, and often human approval."), faq("What is shadow mode?", "Shadow mode lets an AI system produce an output alongside the existing process without changing the live outcome. It provides comparison data before a controlled release."), faq("How do you stop an AI workflow safely?", "Provide an operational kill switch, bounded permissions, queue controls, alerting, a fallback process, and an owner who is responsible for responding to failures.")], sources: common.ai, serviceHref: "/scale/ai-automations",
  },
  {
    slug: "production-ready-ai-agent-architecture", cluster: "AI and automation", title: "What does a production-ready AI agent need?",
    description: "The practical architecture behind tool use, retrieval, structured outputs, cost controls, evaluation, and safe rollout.", published: "2026-08-25", modified: "2026-08-25", readTime: "9 min read",
    lead: "A production AI agent is an application with a model inside it. The model is only one component. Reliability comes from the interfaces around it: scoped tools, typed outputs, retrieval controls, observability, and a path back to a person.",
    sections: [section("Give tools narrow contracts", "Each tool should have a small input schema, an explicit permission boundary, a timeout, and a clear error response. Prefer several constrained tools to one powerful tool with hidden behaviour.", "Keep side effects behind a confirmation or policy layer. Never assume that a model generated a valid identifier simply because it matched a natural language pattern."), section("Make retrieval accountable", "Use approved sources, meaningful document metadata, access-aware retrieval, and citations or source IDs in the result. Test stale, conflicting, missing, and malicious retrieved content.", "A retrieval system should be able to say that it does not have enough evidence. That refusal is often more valuable than a fluent guess."), section("Operate the agent like software", "Track traces, tool calls, token use, latency, errors, escalations, and user feedback. Maintain a versioned evaluation set and test changes before release.", "Set budgets and rate limits, keep a fallback workflow, and design for provider or model changes. Production readiness includes the day two plan, not just the first successful run.")],
    conclusion: "The dependable agent is the one whose uncertainty is visible and whose permissions are boring. Treat the model as a fallible component inside a well-instrumented application.",
    faqs: [faq("Does a production AI agent need retrieval augmented generation?", "Only when the task depends on external, private, or changing knowledge. Retrieval adds value when source access, freshness, permissions, and evaluation are designed properly."), faq("How should AI agent outputs be validated?", "Use typed schemas, business rules, source checks, permission checks, and human review where the impact warrants it. Do not validate only whether the output sounds plausible."), faq("What is the biggest difference between a demo and production?", "Production has real failure handling, access control, monitoring, evaluation, cost limits, ownership, and a recovery path. A demo usually proves only that one happy path can work.")], sources: common.ai, serviceHref: "/scale/ai-agents",
  },
  {
    slug: "measure-ai-automation-performance", cluster: "AI and automation", title: "How to measure whether AI automation is working",
    description: "Measure quality, exceptions, review effort, cost, time saved, adoption, and downstream results instead of demo quality.", published: "2026-08-25", modified: "2026-08-25", readTime: "7 min read",
    lead: "An AI automation is working when the process improves for the people and business around it. A model score or impressive example is not enough. Measure the baseline, the intervention, and the outcome.",
    sections: [section("Set the baseline first", "Record current completion time, error rate, manual touches, queue age, cost, and customer outcome. Segment the data by task type so easy cases do not hide failures in the important ones.", "Define what a good result means before launch. Otherwise the team will optimise for whatever number is easiest to show."), section("Measure quality and friction", "Track accepted output, correction rate, escalation, refusal quality, reviewer time, latency, and cost per completed task. Capture user feedback and sample failures for qualitative review.", "A system that saves seconds but adds a slow review queue may not improve the process. Count the full workflow, not only model response time."), section("Connect metrics to the business", "Link operational changes to conversion, retention, resolution, margin, or another real outcome. Use a controlled rollout or comparison group when the environment allows it.", "Review performance by version and input mix. Keep a rollback threshold and revisit the measure when the workflow changes.")],
    conclusion: "Measurement protects the business from both hype and premature pessimism. Keep the baseline, inspect the exceptions, and judge automation by the complete outcome it creates.",
    faqs: [faq("What is the most important AI automation metric?", "There is no single universal metric. Start with the business outcome, then pair it with quality, exception rate, review effort, and cost so improvement cannot hide a new operational risk."), faq("Should AI automation optimise for accuracy or speed?", "It depends on the task and the cost of failure. Measure both, then choose the threshold that produces the best complete workflow outcome."), faq("How often should AI automation be reviewed?", "Review on a regular operating cadence and after changes to models, prompts, tools, data, policy, or workflow inputs. High-impact tasks need closer monitoring and clearer pause criteria.")], sources: common.ai, serviceHref: "/scale/analytics",
  },
  {
    slug: "choose-technical-seo-development-partner", cluster: "Proof and planning", title: "How to choose a technical SEO and development partner",
    description: "The questions that reveal who owns the work, how delivery is governed, and whether the evidence is real.", published: "2026-08-25", modified: "2026-08-25", readTime: "6 min read",
    lead: "The right partner can explain what will change in the site, how it will be measured, and what remains uncertain. Look for evidence of working systems, clear ownership, and a delivery process that survives contact with production.",
    sections: [section("Ask to see the mechanism", "Request examples of technical findings, content briefs, release checks, performance traces, or integration runbooks. A portfolio image shows an outcome; a working method shows whether it can be repeated.", "Ask which work is done in-house, who reviews it, and who owns the repositories, accounts, data, and deployment after handover."), section("Test the measurement plan", "A credible plan names the baseline, target pages, implementation changes, validation method, time horizon, and leading and lagging indicators. Be cautious with guaranteed rankings or citation promises.", "For performance, ask whether the partner distinguishes lab results from field data. For SEO, ask how they will separate technical defects from intent, content, and authority problems."), section("Check the working relationship", "Agree how decisions are recorded, how risks are escalated, how access is protected, and what happens when a test fails. A partner should make tradeoffs visible, not hide them behind jargon.", "The best engagement leaves the internal team with clearer systems, documentation, and confidence to maintain the work.")],
    conclusion: "Choose the partner who can show the work, name the constraints, and measure what changes. Technical growth is a delivery relationship, not a collection of impressive promises.",
    faqs: [faq("What should a technical SEO partner deliver?", "Depending on scope, expect prioritised findings, implementation or clear tickets, content and internal linking guidance, validation, measurement, documentation, and a review of what changed."), faq("Can an agency guarantee rankings or AI citations?", "No responsible partner can guarantee them. Search systems, competition, location, prompts, and indexes change. A partner can commit to work, evidence, and transparent measurement."), faq("Should the partner own our website accounts?", "The client should retain ownership of domains, analytics, Search Console, repositories, and critical credentials. Partners need appropriate access, not permanent control.")], sources: [...common.geo, ...common.vitals], serviceHref: "/about",
  },
  {
    slug: "seo-writing-guide", cluster: "Search and GEO", title: "SEO writing: how to create content that earns visibility",
    description: "A practical SEO writing process for choosing a search query, matching intent, building a useful outline, adding evidence, and improving content for Google and AI search.", published: "2026-08-25", modified: "2026-08-25", readTime: "12 min read",
    lead: "SEO writing is not inserting a keyword into a blank page. It is the discipline of answering a defined search need better than the available alternatives, then making that answer easy to discover, scan, verify, and act on.",
    sections: [
      section("1. Choose one primary search query", "Start with the question or task your reader is trying to complete. Use Search Console data, customer calls, sales questions, keyword tools, and competitor pages to build a candidate list. Pick one primary query that is relevant to the business, specific enough to answer, and realistic for the site's current authority.", "For example, a page titled 'SEO writing' should not also try to be the definitive guide to technical audits, link building, and AI agents. Those are separate intents. A focused page can rank for natural variations such as 'how to write for SEO' without becoming a bag of unrelated terms."),
      section("2. Map secondary keywords to questions", "Related phrases are useful when they represent sub-questions a reader genuinely needs answered. Group them by meaning rather than repeating every wording. For SEO writing, that might include search intent, SEO headings, internal links, title tags, meta descriptions, readability, and content updates.", "Turn each meaningful group into a possible section. If a phrase does not change the answer, do not create a thin paragraph for it. Search engines do not need a page to repeat the same idea in ten forms."),
      section("3. Analyse the result format", "Inspect the current results for the primary query. Record whether the useful results are step-by-step guides, definitions, comparisons, templates, or examples. Note the questions they answer, the depth they provide, the people they are written for, and the gaps that remain.", "The result page is evidence about intent, not a script to copy. If people want a process, give them a process. If they need to compare choices, make the comparison explicit. A beautifully written article in the wrong format is still a poor answer."),
      section("4. Build an outline before drafting", "Write the H1 first, then the H2s in the order a reader needs them. Add the decision, example, evidence, or action each section must contain. Use H3s only where a subsection helps a reader navigate a real part of the task.", "A useful outline for this topic is: what SEO writing means, how to choose the query, how to understand intent, how to structure the draft, how to use keywords naturally, how to add links and evidence, how to write metadata, how to review, and what to measure after launch."),
      section("5. Write the answer before the background", "Give the direct answer near the top. Then add the reasoning, steps, examples, caveats, and next action. Keep paragraphs short, use concrete verbs, and replace claims such as 'boost visibility' with the mechanism that might cause an improvement.", "A weak sentence says, 'Use headings to improve SEO.' A useful sentence says, 'Use an H2 for each distinct question so a reader can scan to the answer and the page has a clear section boundary.' The second sentence gives the reader something to do."),
      section("6. Use keywords as labels, not decoration", "Place the primary query where it accurately describes the page, including the title, H1, introduction, URL where sensible, and at least one relevant heading. Use related terms where they make the explanation clearer. Never force a phrase into a sentence that a human would not write.", "Do not chase a target density. Read the article aloud and remove repetition. A page can be relevant without using the exact keyword in every heading, because meaning comes from the complete subject, entities, examples, and relationships."),
      section("7. Add first-hand evidence and sources", "Explain what you observed, tested, built, measured, or decided. Where a claim depends on a current standard or external research, link to the original source and distinguish its guidance from your own judgement.", "Google's people-first guidance asks whether content adds original information and whether readers can understand who created it. An author name, author profile, review date, method note, and source list make accountability visible. They do not replace accuracy, but they make it possible to assess."),
      section("8. Build useful internal links", "Link from the article to the service or product page that solves the next problem, and link to other articles that explain a supporting concept. Use anchor text that describes the destination, such as 'technical SEO audit' rather than 'click here'.", "A link should help a reader continue their task. For this guide, a natural next step is the site's on-page SEO service, while a technical reader may need the technical SEO audit guide."),
      section("9. Write the search result before publishing", "Create a concise title tag that states the subject and a meta description that explains the benefit or scope. Keep both accurate. They are promises to the searcher, not places to stack adjectives.", "Use a short, descriptive slug such as /blog/seo-writing-guide. Avoid dates unless the URL genuinely represents a time-bound edition. Keep the visible H1, title metadata, description, and article content aligned so users know they reached the right page."),
      section("10. Make the page easy for agents to parse", "Use semantic HTML, one H1, descriptive H2s, answer-first paragraphs, lists for sequences, visible sources, and stable links. Add BlogPosting and BreadcrumbList markup that reflects the page. Add FAQ markup only for questions and answers that are visible and useful to readers.", "Structured data can clarify what a page is, but it cannot manufacture authority. The content, author, links, and evidence must stand on their own when a person opens the page from a search result or an AI citation."),
      section("11. Review the draft like an editor", "Ask someone who was not involved in the draft to find the missing step, unsupported claim, confusing phrase, and section that does not answer its heading. Check the article against the intended reader and result format.", "Run a final factual and technical pass: check dates, source URLs, internal links, headings, spelling, accessibility, mobile wrapping, metadata, canonical output, and structured data. A review is part of publishing quality, not a cosmetic step after the work is finished."),
      section("12. Measure and improve after publication", "Record the baseline before making changes. After publication, watch impressions, clicks, query mix, engaged visits, enquiries, scroll behaviour, and assisted conversions. For AI visibility, observe a defined set of representative prompts and record the date, location, answer, and cited sources.", "Update when the answer, evidence, guidance, or customer need changes. Do not refresh a date without improving the page. Search performance is a feedback loop, not proof that every decision was right on the first draft."),
    ],
    conclusion: "Strong SEO writing combines a narrow search job with a complete human answer. Choose the query, understand the intent, show your work, make the page easy to navigate and verify, then improve it using evidence from real use.",
    faqs: [faq("What is SEO writing?", "SEO writing is creating useful content around a defined search need and structuring it so people and search systems can discover, understand, verify, and use the answer."), faq("How many keywords should an SEO article target?", "Choose one primary query and cover related phrases only when they represent natural variations or useful sub-questions. A page should own one coherent intent, not a fixed keyword count."), faq("Does AI-generated content rank in Google?", "Google evaluates content by usefulness, originality, accuracy, and whether it is created for people. AI assistance does not remove the need for expertise, review, accountability, and original value."), faq("How long should an SEO article be?", "Long enough to satisfy the search task and no longer. There is no universal preferred word count. Coverage, clarity, evidence, and usefulness matter more than hitting a number."), faq("How often should SEO content be updated?", "Review it when the topic, sources, customer need, or business offering changes. Make a substantive improvement and record the modified date only when the content has genuinely been reviewed.")],
    sources: [...common.geo, { label: "Semrush: 12 SEO writing tips", href: "https://www.semrush.com/blog/seo-writing/" }], serviceHref: "/grow/on-page-seo",
  },
];

export function getBlogPost(slug: string) {
  const post = BLOG_POSTS.find((item) => item.slug === slug);
  return post ? { ...post, ...briefs[slug] } : undefined;
}
