import { SITE } from "@/lib/site";

/* One share card per page, generated by /og. Use in metadata.openGraph on
   any page that has no real screenshot of its own. Pages with a real image
   (case studies, pricing, posts with a hero) list the card first and the
   screenshot second, so the share preview reads as a headline and the
   screenshot remains available to platforms that pick a second image. */
export function ogCard(title: string, kicker: string) {
  const url = `${SITE.url}/og?t=${encodeURIComponent(title)}&k=${encodeURIComponent(kicker)}`;
  return { url, width: 1200, height: 630, alt: title };
}
