#!/usr/bin/env node
/* Integration logo fetcher.
   ---------------------------------------------------------------------------
   Pulls brand marks from Simple Icons, which is CC0 licensed, and writes them
   to /public/integrations/<slug>.svg tinted with each brand's official hex.

   Run once, then again whenever tools are added to src/lib/integrations.ts:

     node scripts/fetch-logos.mjs
     node scripts/fetch-logos.mjs --report   # list what is missing, fetch nothing

   No dependencies. Node 18+ has fetch built in.

   WHY SVG AND NOT WEBP. Emmanuel's rule is that every image is WebP, and that
   is right for photographs and screenshots. A logo is not a photograph. It is
   vector line art, so SVG is smaller (most of these are under 1KB against 3 to
   6KB as WebP), stays sharp at any density, and can be tinted in CSS. Rasterising
   a logo to WebP makes it bigger and worse. The optimise-images script skips SVG
   for exactly this reason. Screenshots and photos still go through WebP.

   Simple Icons ships monochrome paths plus the official brand colour. Tinting
   each mark with its own hex gives a grid that is both recognisable and visually
   consistent, which a set of scraped full colour PNGs at mismatched crops and
   weights never is.

   Anything Simple Icons does not carry is reported at the end. For those, take
   the official asset from the company's own brand page. Never screenshot a
   homepage.
   -------------------------------------------------------------------------- */

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "public", "integrations");
const SOURCE = join(ROOT, "src", "lib", "integrations.ts");

const REPORT_ONLY = process.argv.includes("--report");

/* Our slug to the Simple Icons slug, where they differ. Simple Icons strips
   punctuation and lowercases, so most match already. */
const ALIASES = {
  "google-gemini": "googlegemini",
  "xai-grok": "x",
  "microsoft-teams": "microsoftteams",
  "whatsapp-business": "whatsapp",
  "google-sheets": "googlesheets",
  "google-search-console": "googlesearchconsole",
  "google-analytics": "googleanalytics",
  "google-ads": "googleads",
  "meta-ads": "meta",
  "linkedin-ads": "linkedin",
  "looker-studio": "googledatastudio",
  "screaming-frog": null, // not in Simple Icons, needs the official asset
  nextjs: "nextdotjs",
  postgresql: "postgresql",
  bigquery: "googlebigquery",
  attio: null,
  paystack: null,
  workato: null,
  n8n: "n8n",
};

/* Read slug and brand straight out of the data file, so this never drifts. */
const source = await readFile(SOURCE, "utf8");
const entries = [];
const re = /slug:\s*"([^"]+)",\s*\n\s*name:\s*"([^"]+)",\s*\n\s*url:[^\n]+\n\s*brand:\s*"(#[0-9A-Fa-f]{6})"/g;
let match;
while ((match = re.exec(source))) {
  entries.push({ slug: match[1], name: match[2], brand: match[3] });
}

if (entries.length === 0) {
  console.error("Parsed no integrations. Has the shape of integrations.ts changed?");
  process.exit(1);
}

console.log(`Found ${entries.length} integrations.\n`);

if (REPORT_ONLY) {
  const manual = entries.filter((e) => ALIASES[e.slug] === null);
  console.log(`${entries.length - manual.length} available from Simple Icons.`);
  console.log(`${manual.length} need the official asset:`);
  for (const e of manual) console.log(`  ${e.name}`);
  process.exit(0);
}

await mkdir(OUT, { recursive: true });

const missing = [];
let written = 0;

for (const entry of entries) {
  const alias = ALIASES[entry.slug];
  if (alias === null) {
    missing.push(entry);
    continue;
  }
  const iconSlug = alias ?? entry.slug.replace(/-/g, "");
  const url = `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${iconSlug}.svg`;

  try {
    const response = await fetch(url);
    if (!response.ok) {
      missing.push(entry);
      continue;
    }
    let svg = await response.text();

    /* Tint with the official brand colour. Simple Icons paths carry no fill,
       so this sets one rather than overriding the brand's own. */
    svg = svg.replace("<svg", `<svg fill="${entry.brand}"`);

    await writeFile(join(OUT, `${entry.slug}.svg`), svg, "utf8");
    written += 1;
    process.stdout.write(".");
  } catch {
    missing.push(entry);
  }
}

console.log(`\n\nWrote ${written} marks to public/integrations/`);

/* Emit a manifest of which slugs have a mark on disk. The component reads this
   rather than touching the filesystem, so it stays a server component with no
   runtime IO, and a missing file can never break a static build. */
const have = entries
  .filter((entry) => !missing.includes(entry))
  .map((entry) => entry.slug)
  .sort();

const manifest = `/* GENERATED by scripts/fetch-logos.mjs. Do not edit by hand.
   Slugs with a mark present at /public/integrations/<slug>.svg.
   Anything absent renders as a wordmark tile instead. Re-run the script after
   adding a logo manually. */

export const LOGO_SLUGS = new Set<string>([
${have.map((slug) => `  "${slug}",`).join("\n")}
]);
`;

await writeFile(join(ROOT, "src", "lib", "integration-logos.ts"), manifest, "utf8");
console.log(`Manifest written with ${have.length} slugs.`);

if (missing.length) {
  console.log(`\n${missing.length} not on Simple Icons. Take the official asset`);
  console.log("from each company's brand page and save as the slug below:\n");
  for (const entry of missing) {
    console.log(`  public/integrations/${entry.slug}.svg   (${entry.name})`);
  }
  console.log("\nThen re-run this script to refresh the manifest.");
  console.log("Until then those render as a wordmark tile, which is fine.\n");
}
